<?php
session_start();

if (!isset($_SESSION['username'])) {
    header("Location: ../login.php");
    exit();
}

$username = $_SESSION['username'];
$pageTitle = "Benchmarking and Comparative Analysis";

// Database connection
require_once __DIR__ . '/../config/config.php';
$conn = getDBConnection();

if (!function_exists('formatLegislativeDocumentHtml')) {
    function formatLegislativeDocumentHtml($content) {
        if (empty($content)) return '';

        // Strip duplicate summary header prefix if === LEGAL DOCUMENTS === marker is present
        if (strpos($content, '=== LEGAL DOCUMENTS ===') !== false) {
            $parts = explode('=== LEGAL DOCUMENTS ===', $content, 2);
            $content = trim($parts[1]);
        }

        $lines = explode("\n", $content);
        $html = '<div class="legislative-report-body space-y-4 text-slate-900 font-serif">';
        $in_doc_card = false;

        foreach ($lines as $line) {
            $trimmed = trim($line);

            if (empty($trimmed)) {
                continue;
            }

            // Match === MAIN TITLE / SECTION ===
            if (preg_match('/^===\s*(.*?)\s*===$/', $trimmed, $matches)) {
                if ($in_doc_card) {
                    $html .= '</div></div>';
                    $in_doc_card = false;
                }
                $title = htmlspecialchars($matches[1]);
                $html .= '<div class="my-4 pt-3 border-b-2 border-slate-900 pb-1.5"><h3 class="text-base font-bold uppercase tracking-wide text-slate-900 font-serif">' . $title . '</h3></div>';
            }
            // Match --- Document N: Title ---
            elseif (preg_match('/^---\s*Document\s*(\d+):\s*(.*?)\s*---$/', $trimmed, $matches)) {
                if ($in_doc_card) {
                    $html .= '</div></div>';
                }
                $doc_num = htmlspecialchars($matches[1]);
                $doc_title = htmlspecialchars($matches[2]);
                $in_doc_card = true;
                $html .= '<div class="legal-document-card bg-white p-4 rounded-lg border border-slate-300 shadow-sm my-3 print:border-slate-400 print:shadow-none"><div class="border-b border-slate-200 pb-2 mb-3"><h4 class="text-sm font-bold text-slate-900 font-serif"><i class="fa-solid fa-file-contract text-indigo-700 mr-2 no-print"></i>Document ' . $doc_num . ': ' . $doc_title . '</h4></div><div class="space-y-2">';
            }
            // Match Divider ---
            elseif (preg_match('/^-{10,}$/', $trimmed)) {
                if ($in_doc_card) {
                    $html .= '</div></div>';
                    $in_doc_card = false;
                }
            }
            // Match Metadata Lines
            elseif (preg_match('/^(Document ID|Generated By|Generated Date|Benchmark ID|Assessment ID|Policy Title|Department|Impact Rating|Impact Percentage|Effectiveness|Efficiency|Relevance|Sustainability|Equity|Implementation Rate|Budget Utilization|Beneficiaries):\s*(.*)$/', $trimmed, $matches)) {
                $key = htmlspecialchars($matches[1]);
                $val = htmlspecialchars($matches[2]);
                $html .= '<div class="text-xs text-slate-800 font-medium py-0.5"><span class="font-bold text-slate-900 font-sans">' . $key . ':</span> <span class="font-mono text-indigo-700">' . $val . '</span></div>';
            }
            // Normal paragraph text
            else {
                $html .= '<p class="text-[13px] leading-relaxed text-slate-800 text-justify mb-2 font-serif" style="text-indent: 1.25rem;">' . htmlspecialchars($trimmed) . '</p>';
            }
        }

        if ($in_doc_card) {
            $html .= '</div></div>';
        }

        $html .= '</div>';
        return $html;
    }
}

// Scalable Search & Server-Side Pagination
$search_term = trim($_GET['search'] ?? '');
$rating_filter = trim($_GET['rating'] ?? '');
$status_filter = trim($_GET['status'] ?? '');
$current_page = max(1, intval($_GET['page'] ?? 1));
$items_per_page = max(5, min(100, intval($_GET['limit'] ?? 10)));
$offset = ($current_page - 1) * $items_per_page;

$where_clauses = [];
if (!empty($search_term)) {
    $esc_search = $conn->real_escape_string($search_term);
    $where_clauses[] = "(benchmark_id LIKE '%$esc_search%' OR policy_title LIKE '%$esc_search%' OR department LIKE '%$esc_search%' OR submitted_by LIKE '%$esc_search%')";
}
if (!empty($rating_filter) && $rating_filter != 'All Impact Ratings') {
    $esc_rating = $conn->real_escape_string($rating_filter);
    $where_clauses[] = "impact_rating = '$esc_rating'";
}
if (!empty($status_filter) && $status_filter != 'All Status') {
    $esc_status = $conn->real_escape_string($status_filter);
    $where_clauses[] = "status = '$esc_status'";
}

$where_sql = !empty($where_clauses) ? ' WHERE ' . implode(' AND ', $where_clauses) : '';

// Get total count for pagination calculation
$total_rows_result = $conn->query("SELECT COUNT(*) as count FROM benchmarking_submissions" . $where_sql);
$total_rows = $total_rows_result ? intval($total_rows_result->fetch_assoc()['count']) : 0;
$total_pages = max(1, ceil($total_rows / $items_per_page));

// Get paginated submissions
$submissions_sql = "SELECT * FROM benchmarking_submissions" . $where_sql . " ORDER BY submitted_date DESC LIMIT $offset, $items_per_page";
$submissions_result = $conn->query($submissions_sql);

// Get global KPI counts
$total_submissions = $conn->query("SELECT COUNT(*) as count FROM benchmarking_submissions")->fetch_assoc()['count'];
$pending_count = $conn->query("SELECT COUNT(*) as count FROM benchmarking_submissions WHERE status = 'Pending Comparison'")->fetch_assoc()['count'];
$completed_count = $conn->query("SELECT COUNT(*) as count FROM benchmarking_submissions WHERE status = 'Completed'")->fetch_assoc()['count'];
$evaluated_count = $conn->query("SELECT COUNT(*) as count FROM benchmarking_submissions WHERE status = 'Evaluated'")->fetch_assoc()['count'];
$high_impact_count = $conn->query("SELECT COUNT(*) as count FROM benchmarking_submissions WHERE impact_rating = 'High'")->fetch_assoc()['count'];

// Get single submission for analysis view
$analysis_benchmark_id = isset($_GET['analyze']) ? $_GET['analyze'] : '';
$analysis_data = null;
$analysis_assessment = null;
$matrix_evaluation = null;

if (!empty($analysis_benchmark_id)) {
    $analysis_sql = "SELECT * FROM benchmarking_submissions WHERE benchmark_id = '$analysis_benchmark_id'";
    $analysis_result = $conn->query($analysis_sql);
    if ($analysis_result && $analysis_result->num_rows > 0) {
        $analysis_data = $analysis_result->fetch_assoc();
        
        // Get associated assessment data
        if (!empty($analysis_data['assessment_id'])) {
            $assess_sql = "SELECT * FROM impact_assessments WHERE assessment_id = '" . $analysis_data['assessment_id'] . "'";
            $assess_result = $conn->query($assess_sql);
            if ($assess_result && $assess_result->num_rows > 0) {
                $analysis_assessment = $assess_result->fetch_assoc();
            }
        }
        
        // Get matrix evaluation if exists
        $matrix_sql = "SELECT * FROM benchmarking_matrix WHERE benchmark_id = '$analysis_benchmark_id'";
        $matrix_result = $conn->query($matrix_sql);
        if ($matrix_result && $matrix_result->num_rows > 0) {
            $matrix_evaluation = $matrix_result->fetch_assoc();
        }
    }
}

// Handle matrix evaluation submission
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['save_matrix'])) {
    if (!hasRole([ROLE_ADMIN, ROLE_RESEARCHER])) {
        $_SESSION['toast'] = ['type' => 'error', 'title' => 'Access Denied', 'message' => 'You do not have permission to evaluate benchmark matrix.'];
        header("Location: benchmarking-analysis.php");
        exit();
    }
    $benchmark_id = $_POST['benchmark_id'];
    
    // Comparison Matrix Criteria - 10 criteria (1-10 scale)
    $criteria1 = intval($_POST['criteria1']);
    $criteria2 = intval($_POST['criteria2']);
    $criteria3 = intval($_POST['criteria3']);
    $criteria4 = intval($_POST['criteria4']);
    $criteria5 = intval($_POST['criteria5']);
    $criteria6 = intval($_POST['criteria6']);
    $criteria7 = intval($_POST['criteria7']);
    $criteria8 = intval($_POST['criteria8']);
    $criteria9 = intval($_POST['criteria9']);
    $criteria10 = intval($_POST['criteria10']);
    $comments = $conn->real_escape_string($_POST['comments']);
    
    // Calculate total and average (out of 10)
    $total = $criteria1 + $criteria2 + $criteria3 + $criteria4 + $criteria5 + 
             $criteria6 + $criteria7 + $criteria8 + $criteria9 + $criteria10;
    $average = round($total / 10, 1);
    
    // Determine overall rating based on 10-point scale
    if ($average >= 9.0) $rating = 'Excellent';
    elseif ($average >= 7.5) $rating = 'Good';
    elseif ($average >= 6.0) $rating = 'Fair';
    elseif ($average >= 4.0) $rating = 'Poor';
    else $rating = 'Very Poor';
    
    // Determine recommendation based on 10-point scale
    if ($average >= 8.0) {
        $recommendation = 'Strongly Recommend for Adoption';
    } elseif ($average >= 6.5) {
        $recommendation = 'Recommend with Amendments';
    } elseif ($average >= 4.5) {
        $recommendation = 'Needs Significant Revision';
    } else {
        $recommendation = 'Not Recommended';
    }
    
    // Check if exists
    $check_sql = "SELECT * FROM benchmarking_matrix WHERE benchmark_id = '$benchmark_id'";
    $check_result = $conn->query($check_sql);
    
    if ($check_result && $check_result->num_rows > 0) {
        // Update
        $update_sql = "UPDATE benchmarking_matrix SET 
                       criteria1 = '$criteria1', criteria2 = '$criteria2', criteria3 = '$criteria3',
                       criteria4 = '$criteria4', criteria5 = '$criteria5', criteria6 = '$criteria6',
                       criteria7 = '$criteria7', criteria8 = '$criteria8', criteria9 = '$criteria9',
                       criteria10 = '$criteria10',
                       average_score = '$average', rating = '$rating', 
                       recommendation = '$recommendation',
                       comments = '$comments',
                       evaluated_by = '$username', evaluated_date = NOW()
                       WHERE benchmark_id = '$benchmark_id'";
        $conn->query($update_sql);
    } else {
        // Insert
        $insert_sql = "INSERT INTO benchmarking_matrix 
                       (benchmark_id, criteria1, criteria2, criteria3, criteria4, criteria5, 
                        criteria6, criteria7, criteria8, criteria9, criteria10,
                        average_score, rating, recommendation, comments, evaluated_by, evaluated_date)
                       VALUES 
                       ('$benchmark_id', '$criteria1', '$criteria2', '$criteria3', '$criteria4', '$criteria5',
                        '$criteria6', '$criteria7', '$criteria8', '$criteria9', '$criteria10',
                        '$average', '$rating', '$recommendation', '$comments', '$username', NOW())";
        $conn->query($insert_sql);
    }
    
    // Update submission status
    $conn->query("UPDATE benchmarking_submissions SET status = 'Evaluated' WHERE benchmark_id = '$benchmark_id'");
    
    // Redirect to refresh
    header("Location: benchmarking-analysis.php?analyze=" . urlencode($benchmark_id) . "&matrix_saved=1");
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Benchmarking and Comparative Analysis</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background: #F1F5F9;
        }
        
        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(15, 23, 42, 0.65);
            backdrop-filter: blur(4px);
            overflow-y: auto;
            padding: 20px 10px;
        }
        
        .modal-content {
            background-color: white;
            margin: 2% auto;
            padding: 0;
            border-radius: 16px;
            width: 100%;
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
            animation: slideIn 0.3s ease-out;
            max-height: 90vh;
            display: flex;
            flex-direction: column;
            overflow: hidden;
        }
        
        @keyframes slideIn {
            from { transform: translateY(-30px); opacity: 0; }
            to { transform: translateY(0); opacity: 1; }
        }

        .print-watermark, .print-header, .print-signature-block {
            display: none !important;
        }

@media print {

  /* ---------- 1. PAGE SETUP & MAXIMUM PRINTABLE AREA ---------- */
  @page {
    size: A4 portrait;
    margin: 0.3in 0.35in;
  }

  html, body {
    background: #ffffff !important;
    color: #0f172a !important;
    font-size: 11pt !important;
    line-height: 1.45 !important;
    font-family: 'Times New Roman', Georgia, serif !important;
    margin: 0 !important;
    padding: 0 !important;
    width: 100% !important;
  }

  /* HIDE ALL BACKGROUND PAGE LAYOUT (SIDEBAR, NAVBAR, BREADCRUMBS, TABLES) */
  aside, nav, header, footer,
  .ml-72 > nav,
  main > div:not(#analysisModal),
  main > h1, main > p, main > div.flex {
    display: none !important;
  }

  .ml-72, main {
    margin-left: 0 !important;
    padding: 0 !important;
    margin: 0 !important;
    width: 100% !important;
    max-width: 100% !important;
  }

  h1 { font-size: 17pt !important; margin-bottom: 4pt !important; }
  h2 { font-size: 14pt !important; margin-bottom: 4pt !important; }
  h3 { font-size: 12pt !important; margin-bottom: 3pt !important; }
  h4, h5 { font-size: 11pt !important; margin-bottom: 2pt !important; }
  table, th, td { font-size: 10.5pt !important; }

  /* ---------- 2. UNCONSTRAIN CONTAINERS & FULL PAGE WIDTH ---------- */
  #analysisModal,
  .modal-content,
  .modal-body,
  .doc-content,
  .legislative-report-body,
  [class*="max-h-"],
  [class*="overflow-y"],
  [class*="overflow-auto"] {
    max-height: none !important;
    height: auto !important;
    overflow: visible !important;
    overflow-y: visible !important;
    overflow-x: visible !important;
    width: 100% !important;
    max-width: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
  }

  #analysisModal {
    position: absolute !important;
    top: 0 !important;
    left: 0 !important;
    width: 100% !important;
    display: block !important;
    background: transparent !important;
    box-shadow: none !important;
    border: none !important;
    margin: 0 !important;
    padding: 0 !important;
    z-index: 99999 !important;
  }

  .modal-content {
    box-shadow: none !important;
    border: none !important;
    border-radius: 0 !important;
    width: 100% !important;
    max-width: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
    background: transparent !important;
  }

  /* Compact Edge-to-Edge Grid Layout */
  .grid {
    display: flex !important;
    flex-direction: row !important;
    flex-wrap: wrap !important;
    width: 100% !important;
    gap: 8pt !important;
    margin-bottom: 8pt !important;
  }
  .grid > div {
    flex: 1 1 48% !important;
    max-width: 48% !important;
    box-sizing: border-box !important;
  }

  .mb-6, .mb-8, .my-6 {
    margin-bottom: 8pt !important;
  }

  .p-4, .p-6, .p-5 {
    padding: 6pt 8pt !important;
  }

  /* ---------- 3. HIDE UI CHROME ---------- */
  .no-print,
  button, .btn,
  .modal-header .close, .modal-close, [data-dismiss="modal"],
  input[type="radio"], input[type="checkbox"],
  .rating-input-group, .matrix-radio-row,
  form .submit-row {
    display: none !important;
  }

  .card, .panel, .kpi-card, .metric-card, .legal-document-card, .report-box, .bg-slate-50 {
    box-shadow: none !important;
    border: 1px solid #cbd5e1 !important;
    border-radius: 0 !important;
    background: transparent !important;
  }

  /* ---------- 4. COLOR HANDLING ---------- */
  * {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  .badge, .status-badge, .impact-badge, .rating-badge, .recommendation-badge {
    border: 1px solid currentColor !important;
    padding: 1pt 4pt !important;
  }

  /* ---------- 5. PREVENT MID-SENTENCE CUTS & BREAK AT PARAGRAPHS ---------- */
  p, li, blockquote, dt, dd, .legal-document-card, .report-box, tr, td, th {
    orphans: 4 !important;
    widows: 4 !important;
    page-break-inside: avoid !important;
    break-inside: avoid-page !important;
  }

  table, .comparison-matrix, .kpi-scores, .performance-metrics,
  .print-signature-block, .assessment-summary, .matrix-summary, .criteria-card, .doc-content {
    page-break-inside: avoid !important;
    break-inside: avoid-page !important;
  }

  h1, h2, h3, h4, h5, h6 {
    page-break-after: avoid !important;
    break-after: avoid-page !important;
  }

  p, div, td, span {
    word-wrap: break-word !important;
    overflow-wrap: break-word !important;
  }

  /* ---------- 6. COMPACT FORMAL LETTERHEAD (Page 1 Top) ---------- */
  .print-header {
    display: block !important;
    text-align: center;
    padding-bottom: 6pt !important;
    margin-bottom: 10pt !important;
    border-bottom: 2px solid #0f172a;
    width: 100% !important;
  }

  .print-header img {
    width: 45pt !important;
    height: 45pt !important;
    margin: 0 auto 3pt !important;
  }

  .print-header h1 { font-size: 14pt !important; margin: 0 !important; }
  .print-header h2 { font-size: 11pt !important; margin: 0 !important; }
  .print-header p { font-size: 8.5pt !important; margin: 0 !important; }

  /* ---------- 7. REPEATING SEAL WATERMARK (EVERY PAGE) ---------- */
  .print-watermark {
    display: flex !important;
    visibility: visible !important;
    position: fixed !important;
    inset: 0 !important;
    top: 0 !important;
    left: 0 !important;
    width: 100% !important;
    height: 100% !important;
    align-items: center !important;
    justify-content: center !important;
    opacity: 0.08 !important;
    mix-blend-mode: multiply !important;
    z-index: 0 !important;
    pointer-events: none !important;
  }

  .print-watermark img {
    width: 4.8in !important;
    height: 4.8in !important;
    max-width: 80% !important;
    max-height: 80% !important;
    object-fit: contain !important;
    display: block !important;
    margin: auto !important;
  }

  /* ---------- 8. SIGNATURE BLOCK ---------- */
  .print-signature-block {
    display: flex !important;
    justify-content: space-between;
    margin-top: 18pt !important;
    padding-top: 8pt !important;
    border-top: 1px solid #94a3b8;
    font-size: 9pt !important;
    width: 100% !important;
    page-break-inside: avoid !important;
    break-inside: avoid-page !important;
  }

  .print-signature-block .signature-col {
    width: 45%;
    text-align: center;
  }

  .print-signature-block .signature-line {
    border-top: 1px solid #0f172a;
    margin-top: 20pt !important;
    padding-top: 2pt !important;
  }
}
        
        .btn-scale {
            transition: transform 0.2s ease-in-out;
        }
        .btn-scale:hover {
            transform: scale(1.05);
        }
        .status-badge {
            transition: all 0.3s ease;
        }
        .status-badge:hover {
            transform: scale(1.05);
        }
        .card-hover {
            transition: all 0.3s ease;
        }
        .card-hover:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
        }
        .submission-row {
            transition: all 0.3s ease;
        }
        .submission-row:hover {
            background: #f1f5f9 !important;
            transform: translateX(5px);
        }
        .submission-row.high {
            background: #d1fae5 !important;
            border-left: 4px solid #16a34a;
        }
        .submission-row.moderate {
            background: #fef3c7 !important;
            border-left: 4px solid #f59e0b;
        }
        .submission-row.low {
            background: #fee2e2 !important;
            border-left: 4px solid #dc2626;
        }
        .submission-row.completed {
            background: #dbeafe !important;
            border-left: 4px solid #2563eb;
        }
        .submission-row.evaluated {
            background: #ede9fe !important;
            border-left: 4px solid #7c3aed;
        }
        .analyze-btn {
            background: linear-gradient(135deg, #7c3aed, #4f46e5);
            transition: all 0.3s ease;
            color: white;
            border: none;
            cursor: pointer;
            padding: 4px 12px;
            border-radius: 6px;
            font-size: 12px;
            display: inline-flex;
            align-items: center;
            gap: 4px;
        }
        .analyze-btn:hover {
            transform: scale(1.05);
            box-shadow: 0 4px 15px rgba(124, 58, 237, 0.4);
        }
        .action-btn-sm {
            padding: 4px 10px;
            font-size: 12px;
            border-radius: 6px;
            display: inline-flex;
            align-items: center;
            gap: 4px;
        }
        .table-actions {
            display: flex;
            justify-content: center;
            gap: 4px;
            flex-wrap: wrap;
        }
        .impact-meter {
            width: 100%;
            height: 20px;
            border-radius: 10px;
            background: #e5e7eb;
            overflow: hidden;
        }
        .impact-meter-fill {
            height: 100%;
            border-radius: 10px;
            transition: width 1s ease;
            background: linear-gradient(90deg, #f87171, #fbbf24, #34d399);
        }
        .kpi-bar {
            width: 100%;
            height: 8px;
            border-radius: 4px;
            background: #e5e7eb;
            overflow: hidden;
        }
        .kpi-bar-fill {
            height: 100%;
            border-radius: 4px;
            transition: width 1s ease;
            background: linear-gradient(90deg, #7c3aed, #4f46e5);
        }
        .doc-content {
            white-space: pre-wrap;
            font-family: 'Courier New', monospace;
            font-size: 13px;
            line-height: 1.8;
            background: #f8fafc;
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
            max-height: 500px;
            overflow-y: auto;
        }
        .analysis-section {
            display: <?php echo !empty($analysis_data) ? 'block' : 'none'; ?>;
        }
        .toast {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 15px 25px;
            border-radius: 8px;
            color: white;
            z-index: 2000;
            animation: slideInRight 0.5s ease;
        }
        @keyframes slideInRight {
            from { transform: translateX(100px); opacity: 0; }
            to { transform: translateX(0); opacity: 1; }
        }
        .toast-submit { background: #8b5cf6; }
        .toast-success { background: #16a34a; }
        .fade-in { animation: fadeIn 0.5s ease-in; }
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        .matrix-summary {
            background: linear-gradient(135deg, #f8fafc, #ede9fe);
            border: 2px solid #7c3aed;
        }
        .recommendation-badge {
            padding: 8px 16px;
            border-radius: 20px;
            font-weight: 600;
            display: inline-block;
        }
        .recommend-strong {
            background: #d1fae5;
            color: #065f46;
        }
        .recommend-amend {
            background: #fef3c7;
            color: #92400e;
        }
        .recommend-revise {
            background: #fee2e2;
            color: #991b1b;
        }
        .recommend-not {
            background: #fecaca;
            color: #7f1d1d;
        }
        
        /* Rating Number Styles - No circles, just numbers */
        .rating-number {
            display: inline-block;
            padding: 4px 10px;
            font-size: 14px;
            font-weight: 600;
            color: #6b7280;
            transition: all 0.3s ease;
            cursor: pointer;
            user-select: none;
            border-radius: 4px;
            min-width: 30px;
            text-align: center;
        }
        .rating-number:hover {
            background: #faf5ff;
            color: #7c3aed;
            transform: scale(1.05);
        }
        .rating-number.selected {
            background: #7c3aed;
            color: white;
            transform: scale(1.08);
            box-shadow: 0 2px 8px rgba(124, 58, 237, 0.3);
        }
        .criteria-card {
            transition: all 0.3s ease;
            border: 2px solid #e5e7eb;
        }
        .criteria-card:hover {
            border-color: #7c3aed;
            background: #faf5ff;
        }
        .criteria-card.selected {
            border-color: #7c3aed;
            background: #ede9fe;
        }
        .hidden {
            display: none;
        }
        @media print {
            .no-print { display: none !important; }
            body { background: white; }
        }
    </style>
</head>

<body>

<?php include("../includes/sidebar.php"); ?>

<div class="ml-72">

<?php include("../includes/navbar.php"); ?>

<main class="p-8">

    <!-- Toast Notifications -->
    <?php if (isset($_GET['submitted'])): ?>
        <div class="toast toast-submit" id="toast">
            <i class="fa-solid fa-check-circle mr-2"></i>
            Successfully submitted to Benchmarking for Comparative Analysis!
        </div>
        <script>setTimeout(() => { document.getElementById('toast').style.display = 'none'; }, 5000);</script>
    <?php endif; ?>
    
    <?php if (isset($_GET['matrix_saved'])): ?>
        <div class="toast toast-success" id="toast">
            <i class="fa-solid fa-check-circle mr-2"></i>
            Comparison Matrix evaluation saved successfully!
        </div>
        <script>setTimeout(() => { document.getElementById('toast').style.display = 'none'; }, 5000);</script>
    <?php endif; ?>



    <!-- KPI CARDS -->
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-5 gap-6 mb-8 no-print">
        <div class="bg-white rounded-xl shadow p-6 card-hover">
            <div class="flex justify-between">
                <div>
                    <p class="text-slate-500">Total Submissions</p>
                    <h2 class="text-4xl font-bold mt-2"><?php echo $total_submissions; ?></h2>
                </div>
                <div class="w-14 h-14 rounded-full bg-blue-100 flex items-center justify-center">
                    <i class="fa-solid fa-scale-balanced text-blue-700 text-2xl"></i>
                </div>
            </div>
            <p class="text-blue-600 mt-4">In Repository</p>
        </div>

        <div class="bg-white rounded-xl shadow p-6 card-hover">
            <div class="flex justify-between">
                <div>
                    <p class="text-slate-500">Pending Analysis</p>
                    <h2 class="text-4xl font-bold mt-2"><?php echo $pending_count; ?></h2>
                </div>
                <div class="w-14 h-14 rounded-full bg-yellow-100 flex items-center justify-center">
                    <i class="fa-solid fa-clock text-yellow-700 text-2xl"></i>
                </div>
            </div>
            <p class="text-yellow-600 mt-4">Awaiting Review</p>
        </div>

        <div class="bg-white rounded-xl shadow p-6 card-hover">
            <div class="flex justify-between">
                <div>
                    <p class="text-slate-500">Completed</p>
                    <h2 class="text-4xl font-bold mt-2"><?php echo $completed_count; ?></h2>
                </div>
                <div class="w-14 h-14 rounded-full bg-green-100 flex items-center justify-center">
                    <i class="fa-solid fa-check-circle text-green-700 text-2xl"></i>
                </div>
            </div>
            <p class="text-green-600 mt-4">Analyzed</p>
        </div>

        <div class="bg-white rounded-xl shadow p-6 card-hover">
            <div class="flex justify-between">
                <div>
                    <p class="text-slate-500">Evaluated</p>
                    <h2 class="text-4xl font-bold mt-2"><?php echo $evaluated_count; ?></h2>
                </div>
                <div class="w-14 h-14 rounded-full bg-purple-100 flex items-center justify-center">
                    <i class="fa-solid fa-star text-purple-700 text-2xl"></i>
                </div>
            </div>
            <p class="text-purple-600 mt-4">Matrix Completed</p>
        </div>

        <div class="bg-white rounded-xl shadow p-6 card-hover">
            <div class="flex justify-between">
                <div>
                    <p class="text-slate-500">High Impact</p>
                    <h2 class="text-4xl font-bold mt-2"><?php echo $high_impact_count; ?></h2>
                </div>
                <div class="w-14 h-14 rounded-full bg-red-100 flex items-center justify-center">
                    <i class="fa-solid fa-arrow-trend-up text-red-700 text-2xl"></i>
                </div>
            </div>
            <p class="text-red-600 mt-4">Successful Policies</p>
        </div>
    </div>

    <!-- SCALABLE SEARCH & FILTER BAR -->
    <div class="bg-white rounded-xl shadow p-6 mb-8 no-print">
        <form method="GET" action="benchmarking-analysis.php" class="grid lg:grid-cols-4 gap-4">
            <div class="relative">
                <i class="fa-solid fa-magnifying-glass absolute left-3.5 top-3.5 text-slate-400"></i>
                <input type="text" 
                       name="search"
                       value="<?php echo htmlspecialchars($search_term); ?>"
                       onkeyup="liveFilterTable(this.value)"
                       placeholder="Search by policy, ID, department..." 
                       class="w-full border border-slate-300 rounded-lg pl-10 pr-4 py-2.5 text-sm focus:ring-2 focus:ring-purple-600 focus:outline-none">
            </div>
            <select name="rating" onchange="this.form.submit()" class="border border-slate-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-purple-600 focus:outline-none">
                <option value="All Impact Ratings" <?php echo $rating_filter == 'All Impact Ratings' || empty($rating_filter) ? 'selected' : ''; ?>>All Impact Ratings</option>
                <option value="High" <?php echo $rating_filter == 'High' ? 'selected' : ''; ?>>High Impact</option>
                <option value="Moderate" <?php echo $rating_filter == 'Moderate' ? 'selected' : ''; ?>>Moderate Impact</option>
                <option value="Low" <?php echo $rating_filter == 'Low' ? 'selected' : ''; ?>>Low Impact</option>
                <option value="Very Low" <?php echo $rating_filter == 'Very Low' ? 'selected' : ''; ?>>Very Low Impact</option>
            </select>
            <select name="status" onchange="this.form.submit()" class="border border-slate-300 rounded-lg p-2.5 text-sm focus:ring-2 focus:ring-purple-600 focus:outline-none">
                <option value="All Status" <?php echo $status_filter == 'All Status' || empty($status_filter) ? 'selected' : ''; ?>>All Status</option>
                <option value="Pending Comparison" <?php echo $status_filter == 'Pending Comparison' ? 'selected' : ''; ?>>Pending Comparison</option>
                <option value="Completed" <?php echo $status_filter == 'Completed' ? 'selected' : ''; ?>>Completed</option>
                <option value="Evaluated" <?php echo $status_filter == 'Evaluated' ? 'selected' : ''; ?>>Evaluated</option>
            </select>
            <div class="flex gap-2">
                <button type="submit" class="flex-1 bg-purple-700 hover:bg-purple-800 text-white rounded-lg btn-scale font-semibold text-sm py-2.5 flex items-center justify-center gap-2 shadow-sm">
                    <i class="fa-solid fa-search"></i>
                    Search
                </button>
                <?php if (!empty($search_term) || (!empty($rating_filter) && $rating_filter != 'All Impact Ratings') || (!empty($status_filter) && $status_filter != 'All Status')): ?>
                    <a href="benchmarking-analysis.php" class="bg-slate-200 hover:bg-slate-300 text-slate-700 px-3.5 py-2.5 rounded-lg text-sm font-semibold flex items-center justify-center transition" title="Clear Search">
                        <i class="fa-solid fa-rotate-left"></i>
                    </a>
                <?php endif; ?>
            </div>
        </form>
    </div>

    <!-- ========================================= -->
    <!-- POLICY COMPARISON REPOSITORY -->
    <!-- ========================================= -->
    <div class="bg-white rounded-xl shadow mb-8 no-print">
        <div class="flex items-center justify-between px-6 py-5 border-b">
            <div>
                <h2 class="text-2xl font-bold">
                    Policy Comparison Repository
                </h2>
                <p class="text-slate-500 mt-1">
                    Click <strong>"Analyze"</strong> to view the full policy report and evaluate using the Comparison Matrix.
                </p>
            </div>
            <div class="flex items-center gap-2 flex-wrap">
                <a href="../modules/impact-assessment.php" 
                   class="bg-blue-800 hover:bg-blue-900 text-white px-4 py-2 rounded-lg text-sm font-semibold btn-scale flex items-center gap-1.5 shadow-sm">
                    <i class="fa-solid fa-arrow-left"></i> Back to Assessment
                </a>
                <button class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg text-sm font-semibold btn-scale flex items-center gap-1.5 shadow-sm">
                    <i class="fa-solid fa-file-export"></i> Export Report
                </button>
            </div>
        </div>

        <div class="overflow-x-auto">
            <table class="w-full">
                <thead class="bg-slate-100">
                    <tr>
                        <th class="text-left p-4">Benchmark ID</th>
                        <th class="text-left p-4">Policy Title</th>
                        <th class="text-left p-4">Department</th>
                        <th class="text-left p-4">Impact %</th>
                        <th class="text-left p-4">Impact Rating</th>
                        <th class="text-left p-4">Documents</th>
                        <th class="text-left p-4">Status</th>
                        <th class="text-left p-4">Submitted</th>
                        <th class="text-center p-4">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($submissions_result && $submissions_result->num_rows > 0): ?>
                        <?php while($row = $submissions_result->fetch_assoc()): 
                            $row_class = '';
                            if ($row['impact_rating'] == 'High') $row_class = 'high';
                            elseif ($row['impact_rating'] == 'Moderate') $row_class = 'moderate';
                            elseif ($row['impact_rating'] == 'Low') $row_class = 'low';
                            if ($row['status'] == 'Completed') $row_class .= ' completed';
                            if ($row['status'] == 'Evaluated') $row_class .= ' evaluated';
                        ?>
                            <tr class="border-b hover:bg-slate-50 submission-row <?php echo $row_class; ?>">
                                <td class="p-4 font-mono font-bold text-purple-600">
                                    <?php echo htmlspecialchars($row['benchmark_id']); ?>
                                </td>
                                <td class="p-4 font-medium">
                                    <?php echo htmlspecialchars($row['policy_title']); ?>
                                </td>
                                <td class="p-4">
                                    <?php echo htmlspecialchars($row['department']); ?>
                                </td>
                                <td class="p-4">
                                    <div class="flex items-center gap-2">
                                        <span class="font-bold text-indigo-600"><?php echo $row['impact_percentage']; ?>%</span>
                                        <div class="w-16 bg-slate-200 rounded-full h-2">
                                            <div class="h-2 rounded-full" style="width:<?php echo $row['impact_percentage']; ?>%; background: linear-gradient(90deg, #f87171, #fbbf24, #34d399);"></div>
                                        </div>
                                    </div>
                                </td>
                                <td class="p-4">
                                    <span class="status-badge px-3 py-1 rounded-full text-sm font-bold
                                        <?php echo $row['impact_rating'] == 'High' ? 'bg-green-100 text-green-700' : 
                                                  ($row['impact_rating'] == 'Moderate' ? 'bg-yellow-100 text-yellow-700' : 
                                                  ($row['impact_rating'] == 'Low' ? 'bg-orange-100 text-orange-700' : 'bg-red-100 text-red-700')); ?>">
                                        <?php echo htmlspecialchars($row['impact_rating']); ?>
                                    </span>
                                </td>
                                <td class="p-4">
                                    <span class="bg-purple-100 text-purple-700 px-3 py-1 rounded-full text-sm flex items-center gap-1">
                                        <i class="fa-solid fa-gavel mr-1"></i> <?php echo $row['document_count']; ?>
                                    </span>
                                </td>
                                <td class="p-4">
                                    <span class="status-badge px-3 py-1 rounded-full text-sm
                                        <?php echo $row['status'] == 'Completed' ? 'bg-blue-100 text-blue-700' : 
                                                  ($row['status'] == 'Evaluated' ? 'bg-purple-100 text-purple-700' : 'bg-yellow-100 text-yellow-700'); ?>">
                                        <?php echo htmlspecialchars($row['status']); ?>
                                    </span>
                                </td>
                                <td class="p-4 text-sm">
                                    <?php echo date('M j, Y', strtotime($row['submitted_date'])); ?>
                                </td>
                                <td class="p-4 text-center">
                                    <div class="flex justify-center items-center gap-1.5">
                                        <a href="?analyze=<?php echo urlencode($row['benchmark_id']); ?>" 
                                           class="bg-blue-600 hover:bg-blue-700 text-white w-8 h-8 rounded-lg flex items-center justify-center text-xs btn-scale shadow-sm"
                                           title="Analyze & Compare Policy">
                                            <i class="fa-solid fa-magnifying-glass-chart"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="9" class="text-center p-8 text-slate-500">
                                <i class="fa-solid fa-inbox text-4xl block mb-4"></i>
                                No benchmarking submissions found.
                                <p class="text-sm mt-2">Submit policies from the Impact Assessment module.</p>
                                <a href="../modules/impact-assessment.php" class="text-blue-700 hover:underline mt-2 inline-block">
                                    <i class="fa-solid fa-arrow-right mr-1"></i> Go to Impact Assessment
                                </a>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <!-- INTERACTIVE PAGINATION FOOTER -->
        <div class="flex flex-wrap justify-between items-center px-6 py-4 border-t gap-3 no-print">
            <?php 
                $start_entry = $total_rows > 0 ? $offset + 1 : 0;
                $end_entry = min($offset + $items_per_page, $total_rows);
            ?>
            <p class="text-sm text-slate-500 font-medium">
                Showing <strong class="text-slate-800"><?php echo $start_entry; ?></strong> to <strong class="text-slate-800"><?php echo $end_entry; ?></strong> of <strong class="text-slate-800"><?php echo $total_rows; ?></strong> submissions
            </p>

            <div class="flex items-center gap-1.5 flex-wrap">
                <!-- PREVIOUS PAGE BUTTON -->
                <?php if ($current_page > 1): ?>
                    <a href="?page=<?php echo $current_page - 1; ?>&search=<?php echo urlencode($search_term); ?>&rating=<?php echo urlencode($rating_filter); ?>&status=<?php echo urlencode($status_filter); ?>&limit=<?php echo $items_per_page; ?>" 
                       class="border border-slate-300 px-3.5 py-1.5 rounded-lg text-xs font-semibold text-slate-700 hover:bg-slate-100 transition flex items-center gap-1">
                        <i class="fa-solid fa-chevron-left text-[10px]"></i> Prev
                    </a>
                <?php else: ?>
                    <span class="border border-slate-200 px-3.5 py-1.5 rounded-lg text-xs font-semibold text-slate-400 bg-slate-50 cursor-not-allowed flex items-center gap-1 opacity-70">
                        <i class="fa-solid fa-chevron-left text-[10px]"></i> Prev
                    </span>
                <?php endif; ?>

                <!-- PAGE NUMBERS -->
                <?php 
                $start_page = max(1, $current_page - 2);
                $end_page = min($total_pages, $current_page + 2);
                for ($p = $start_page; $p <= $end_page; $p++): 
                ?>
                    <?php if ($p == $current_page): ?>
                        <span class="bg-blue-700 text-white px-3.5 py-1.5 rounded-lg text-xs font-bold shadow-sm">
                            <?php echo $p; ?>
                        </span>
                    <?php else: ?>
                        <a href="?page=<?php echo $p; ?>&search=<?php echo urlencode($search_term); ?>&rating=<?php echo urlencode($rating_filter); ?>&status=<?php echo urlencode($status_filter); ?>&limit=<?php echo $items_per_page; ?>" 
                           class="border border-slate-300 text-slate-700 hover:bg-blue-50 hover:text-blue-700 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition">
                            <?php echo $p; ?>
                        </a>
                    <?php endif; ?>
                <?php endfor; ?>

                <!-- NEXT PAGE BUTTON -->
                <?php if ($current_page < $total_pages): ?>
                    <a href="?page=<?php echo $current_page + 1; ?>&search=<?php echo urlencode($search_term); ?>&rating=<?php echo urlencode($rating_filter); ?>&status=<?php echo urlencode($status_filter); ?>&limit=<?php echo $items_per_page; ?>" 
                       class="border border-slate-300 px-3.5 py-1.5 rounded-lg text-xs font-semibold text-slate-700 hover:bg-slate-100 transition flex items-center gap-1">
                        Next <i class="fa-solid fa-chevron-right text-[10px]"></i>
                    </a>
                <?php else: ?>
                    <span class="border border-slate-200 px-3.5 py-1.5 rounded-lg text-xs font-semibold text-slate-400 bg-slate-50 cursor-not-allowed flex items-center gap-1 opacity-70">
                        Next <i class="fa-solid fa-chevron-right text-[10px]"></i>
                    </span>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <!-- ========================================= -->
    <!-- ANALYSIS SECTION - Shows when Analyze is clicked -->
    <!-- ========================================= -->
    <!-- ========================================= -->
    <!-- ANALYSIS MODAL - Shows when Analyze is clicked -->
    <!-- ========================================= -->
    <?php if ($analysis_data): ?>
    <div id="analysisModal" class="modal" style="display: block;">
        <div class="modal-content max-w-5xl relative overflow-hidden">
            <!-- CENTERED WATERMARK LOGO FOR PRINT ONLY (REPEATED PER PAGE) -->
            <div class="print-watermark hidden print:flex pointer-events-none">
                <img src="../City.jpg" alt="Watermark City Logo" class="w-[500px] h-[500px] object-contain">
            </div>

            <!-- FORMAL PRINT HEADER WITH LOGO & AUTHENTICITY BADGE -->
            <div class="print-header hidden p-6 pb-4 border-b text-center border-slate-300">
                <img src="../City.jpg" alt="City Logo" class="w-20 h-20 rounded-full object-cover border-2 border-slate-300 shadow-sm mx-auto mb-2">
                <h1 class="text-xl font-bold uppercase tracking-wide text-slate-800">Republic of the Philippines</h1>
                <h2 class="text-lg font-semibold text-slate-700">City of San Jose Del Monte, Bulacan</h2>
                <p class="text-sm font-medium text-slate-600">Legislative Research, Policy Analysis & Impact Evaluation System</p>
                <div class="mt-2 inline-block px-3 py-1 bg-slate-100 border border-slate-300 rounded-full text-xs font-semibold text-slate-700">
                    <i class="fa-solid fa-shield-halved text-purple-600 mr-1"></i> Official Benchmarking & Comparative Analysis Report &bull; Verified Authenticity
                </div>
            </div>
            <!-- Analysis Header -->
            <div class="flex items-center justify-between p-6 border-b bg-gradient-to-r from-blue-50 via-indigo-50 to-purple-50">
                <div>
                    <h2 class="text-2xl font-bold flex items-center gap-2 text-slate-800">
                        <i class="fa-solid fa-magnifying-glass-chart text-purple-600"></i>
                        Policy Analysis Report
                    </h2>
                    <p class="text-slate-600 mt-1">
                        <strong><?php echo htmlspecialchars($analysis_data['policy_title']); ?></strong>
                        <span class="text-sm text-slate-500 font-mono ml-2">(<?php echo $analysis_data['benchmark_id']; ?>)</span>
                        <?php if ($analysis_data['impact_rating'] == 'High'): ?>
                            <span class="text-sm bg-green-100 text-green-700 px-2.5 py-1 rounded-full ml-2 font-semibold">
                                <i class="fa-solid fa-check-circle mr-1"></i> High Impact
                            </span>
                        <?php elseif ($analysis_data['impact_rating'] == 'Moderate'): ?>
                            <span class="text-sm bg-yellow-100 text-yellow-700 px-2.5 py-1 rounded-full ml-2 font-semibold">
                                <i class="fa-solid fa-check-circle mr-1"></i> Moderate Impact
                            </span>
                        <?php else: ?>
                            <span class="text-sm bg-orange-100 text-orange-700 px-2.5 py-1 rounded-full ml-2 font-semibold">
                                <i class="fa-solid fa-exclamation-circle mr-1"></i> Low Impact
                            </span>
                        <?php endif; ?>
                        <?php if ($matrix_evaluation): ?>
                            <span class="text-sm bg-purple-100 text-purple-700 px-2.5 py-1 rounded-full ml-2 font-semibold">
                                <i class="fa-solid fa-star mr-1"></i> <?php echo $matrix_evaluation['rating']; ?>
                            </span>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="flex items-center gap-3 no-print">
                    <button onclick="closeAnalysisModal()" class="w-9 h-9 flex items-center justify-center rounded-full bg-slate-200/80 hover:bg-slate-300 text-slate-600 hover:text-slate-800 transition text-xl font-bold" title="Close Modal">
                        &times;
                    </button>
                </div>
            </div>

            <!-- Analysis Content (Scrollable) -->
            <div class="p-6 overflow-y-auto max-h-[65vh]">
                <!-- Policy Summary -->
                <div class="grid md:grid-cols-2 gap-6 mb-6">
                    <div>
                        <h3 class="font-semibold text-slate-700 mb-3">Policy Information</h3>
                        <div class="space-y-2 bg-slate-50 p-4 rounded-lg">
                            <p><strong>Benchmark ID:</strong> <span class="font-mono text-purple-600"><?php echo htmlspecialchars($analysis_data['benchmark_id']); ?></span></p>
                            <p><strong>Assessment ID:</strong> <?php echo htmlspecialchars($analysis_data['assessment_id']); ?></p>
                            <p><strong>Policy Title:</strong> <?php echo htmlspecialchars($analysis_data['policy_title']); ?></p>
                            <p><strong>Department:</strong> <?php echo htmlspecialchars($analysis_data['department']); ?></p>
                            <p><strong>Submitted By:</strong> <?php echo htmlspecialchars($analysis_data['submitted_by']); ?></p>
                            <p><strong>Submitted Date:</strong> <?php echo date('F j, Y h:i A', strtotime($analysis_data['submitted_date'])); ?></p>
                            <p><strong>Status:</strong> 
                                <span class="status-badge px-3 py-1 rounded-full text-sm
                                    <?php echo $analysis_data['status'] == 'Completed' ? 'bg-blue-100 text-blue-700' : 
                                              ($analysis_data['status'] == 'Evaluated' ? 'bg-purple-100 text-purple-700' : 'bg-yellow-100 text-yellow-700'); ?>">
                                    <?php echo htmlspecialchars($analysis_data['status']); ?>
                                </span>
                            </p>
                        </div>
                    </div>
                    <div>
                        <h3 class="font-semibold text-slate-700 mb-3">Impact Summary</h3>
                        <div class="bg-slate-50 p-4 rounded-lg">
                            <div class="text-center">
                                <div class="text-6xl font-bold text-indigo-600 mb-2">
                                    <?php echo $analysis_data['impact_percentage']; ?>%
                                </div>
                                <div class="impact-meter">
                                    <div class="impact-meter-fill" style="width:<?php echo $analysis_data['impact_percentage']; ?>%;"></div>
                                </div>
                                <div class="mt-4">
                                    <span class="status-badge px-4 py-2 rounded-full text-lg font-bold
                                        <?php echo $analysis_data['impact_rating'] == 'High' ? 'bg-green-100 text-green-700' : 
                                                  ($analysis_data['impact_rating'] == 'Moderate' ? 'bg-yellow-100 text-yellow-700' : 
                                                  'bg-orange-100 text-orange-700'); ?>">
                                        <?php echo htmlspecialchars($analysis_data['impact_rating']); ?> Impact
                                    </span>
                                </div>
                                <p class="text-sm text-slate-500 mt-3">
                                    <i class="fa-regular fa-file-lines mr-1"></i> 
                                    <?php echo $analysis_data['document_count']; ?> legal documents included
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- KPI Scores & Performance Metrics (Side-by-Side near Assessment) -->
                <?php if ($analysis_assessment): ?>
                <div class="grid md:grid-cols-2 gap-6 mb-6">
                    <!-- KPI Scores -->
                    <div>
                        <h3 class="font-semibold text-slate-700 mb-3">
                            <i class="fa-solid fa-chart-simple text-purple-600 mr-2"></i>
                            KPI Scores
                        </h3>
                        <div class="space-y-2 bg-slate-50 p-3 rounded-lg border border-slate-200 print:p-2 print:space-y-1">
                            <?php 
                            $kpis = [
                                'Effectiveness' => $analysis_assessment['kpi_effectiveness'] ?? 0,
                                'Efficiency' => $analysis_assessment['kpi_efficiency'] ?? 0,
                                'Relevance' => $analysis_assessment['kpi_relevance'] ?? 0,
                                'Sustainability' => $analysis_assessment['kpi_sustainability'] ?? 0,
                                'Equity' => $analysis_assessment['kpi_equity'] ?? 0
                            ];
                            foreach ($kpis as $label => $value): ?>
                                <div>
                                    <div class="flex justify-between text-xs mb-0.5">
                                        <span><?php echo $label; ?></span>
                                        <span class="font-bold text-indigo-600"><?php echo $value; ?>%</span>
                                    </div>
                                    <div class="kpi-bar h-1.5">
                                        <div class="kpi-bar-fill h-1.5" style="width:<?php echo $value; ?>%;"></div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>

                    <!-- Performance Metrics -->
                    <div>
                        <h3 class="font-semibold text-slate-700 mb-3">
                            <i class="fa-solid fa-gauge-high text-purple-600 mr-2"></i>
                            Performance Metrics
                        </h3>
                        <div class="space-y-3 bg-slate-50 p-4 rounded-lg border border-slate-200">
                            <div class="flex justify-between items-center p-2.5 bg-white rounded border border-slate-200">
                                <span class="text-xs text-slate-600 font-medium">Implementation Rate</span>
                                <span class="text-sm font-bold text-blue-600"><?php echo $analysis_assessment['implementation_rate'] ?? 0; ?>%</span>
                            </div>
                            <div class="flex justify-between items-center p-2.5 bg-white rounded border border-slate-200">
                                <span class="text-xs text-slate-600 font-medium">Budget Utilization</span>
                                <span class="text-sm font-bold text-green-600"><?php echo $analysis_assessment['budget_utilization'] ?? 0; ?>%</span>
                            </div>
                            <div class="flex justify-between items-center p-2.5 bg-white rounded border border-slate-200">
                                <span class="text-xs text-slate-600 font-medium">Beneficiaries</span>
                                <span class="text-sm font-bold text-purple-600"><?php echo number_format($analysis_assessment['beneficiaries'] ?? 0); ?></span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Assessment Summary -->
                <?php if (!empty($analysis_assessment['assessment_summary'])): ?>
                <div class="mb-6">
                    <h3 class="font-semibold text-slate-700 mb-3">
                        <i class="fa-solid fa-align-left text-purple-600 mr-2"></i>
                        Assessment Summary
                    </h3>
                    <div class="bg-slate-50 p-4 rounded-lg">
                        <p class="text-slate-700"><?php echo nl2br(htmlspecialchars($analysis_assessment['assessment_summary'])); ?></p>
                    </div>
                </div>
                <?php endif; ?>
                <?php endif; ?>

                <!-- Legal Documents -->
                <div class="mb-6">
                    <h3 class="font-semibold text-slate-700 mb-3">
                        <i class="fa-solid fa-gavel text-purple-600 mr-2"></i>
                        Legal Documents
                        <span class="text-sm font-normal text-slate-500 ml-2">(<?php echo $analysis_data['document_count']; ?> documents)</span>
                    </h3>
                    <div class="doc-content">
                        <?php 
                        $content = $analysis_data['combined_content'];
                        echo formatLegislativeDocumentHtml($content);
                        ?>
                    </div>
                </div>

                <!-- ========================================= -->
                <!-- COMPARISON MATRIX EVALUATION -->
                <!-- ========================================= -->
                <div class="mt-8 border-t pt-6">
                    <h3 class="text-xl font-bold mb-4 text-indigo-800">
                        <i class="fa-solid fa-table text-purple-600 mr-2"></i>
                        Comparison Matrix Evaluation
                        <span class="text-sm font-normal text-slate-500 ml-2">(1-10 Scale)</span>
                    </h3>
                    
                    <?php if ($matrix_evaluation): ?>
                        <!-- Show existing evaluation -->
                        <div class="matrix-summary rounded-lg mb-4">
                            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 items-stretch border border-slate-200 p-4 rounded-lg bg-slate-50 print:bg-transparent">
                                <!-- Col 1: Evaluated By & Date -->
                                <div class="flex flex-col justify-center bg-white p-3.5 rounded border border-slate-200 print:bg-transparent">
                                    <p class="text-xs text-slate-500 font-medium uppercase tracking-wider">Evaluated By</p>
                                    <p class="font-bold text-slate-900 text-sm"><?php echo htmlspecialchars($matrix_evaluation['evaluated_by']); ?></p>
                                    <p class="text-xs text-slate-500 font-medium uppercase tracking-wider mt-2.5">Evaluated Date</p>
                                    <p class="font-semibold text-slate-800 text-xs font-mono"><?php echo date('F j, Y h:i A', strtotime($matrix_evaluation['evaluated_date'])); ?></p>
                                </div>

                                <!-- Col 2: Average Score -->
                                <div class="flex flex-col items-center justify-center text-center bg-white p-3.5 rounded border border-slate-200 print:bg-transparent">
                                    <p class="text-xs text-slate-500 font-medium uppercase tracking-wider mb-1">Average Score</p>
                                    <p class="text-3xl font-extrabold text-indigo-600 font-mono"><?php echo $matrix_evaluation['average_score']; ?></p>
                                    <p class="text-xs text-slate-500 font-medium">out of 10.0</p>
                                </div>

                                <!-- Col 3: Overall Rating & Recommendation -->
                                <div class="flex flex-col items-center justify-center text-center bg-white p-3.5 rounded border border-slate-200 print:bg-transparent">
                                    <p class="text-xs text-slate-500 font-medium uppercase tracking-wider mb-1">Overall Rating</p>
                                    <div>
                                        <span class="status-badge px-3 py-1 rounded-full text-sm font-bold inline-block
                                            <?php 
                                            $rating = $matrix_evaluation['rating'];
                                            if ($rating == 'Excellent') echo 'bg-green-100 text-green-700 border-green-300';
                                            elseif ($rating == 'Good') echo 'bg-blue-100 text-blue-700 border-blue-300';
                                            elseif ($rating == 'Fair') echo 'bg-yellow-100 text-yellow-700 border-yellow-300';
                                            elseif ($rating == 'Poor') echo 'bg-orange-100 text-orange-700 border-orange-300';
                                            else echo 'bg-red-100 text-red-700 border-red-300';
                                            ?>">
                                            <?php echo htmlspecialchars($matrix_evaluation['rating']); ?>
                                        </span>
                                    </div>
                                    <?php if (!empty($matrix_evaluation['recommendation'])): ?>
                                        <div class="mt-2">
                                            <span class="recommendation-badge text-xs px-2.5 py-1 rounded-full inline-block font-semibold 
                                                <?php 
                                                $rec = $matrix_evaluation['recommendation'];
                                                if ($rec == 'Strongly Recommend for Adoption') echo 'recommend-strong';
                                                elseif ($rec == 'Recommend with Amendments') echo 'recommend-amend';
                                                elseif ($rec == 'Needs Significant Revision') echo 'recommend-revise';
                                                else echo 'recommend-not';
                                                ?>">
                                                <?php echo htmlspecialchars($matrix_evaluation['recommendation']); ?>
                                            </span>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            
                            <div class="mt-4 grid md:grid-cols-2 gap-3">
                                <?php 
                                $criteria_labels = [
                                    1 => 'Alignment with Legal Framework',
                                    2 => 'Compliance with Constitutional Provisions',
                                    3 => 'Consistency with International Law',
                                    4 => 'Protection of Rights and Liberties',
                                    5 => 'Implementation Mechanism',
                                    6 => 'Monitoring and Evaluation',
                                    7 => 'Stakeholder Engagement',
                                    8 => 'Resource Allocation',
                                    9 => 'Risk Assessment',
                                    10 => 'Sustainability'
                                ];
                                for ($i = 1; $i <= 10; $i++):
                                    $value = $matrix_evaluation['criteria' . $i] ?? 0;
                                    $percentage = ($value / 10) * 100;
                                ?>
                                <div class="bg-white p-3 rounded-lg shadow-sm">
                                    <p class="text-sm text-slate-500"><?php echo $i . '. ' . $criteria_labels[$i]; ?></p>
                                    <div class="flex items-center gap-2">
                                        <span class="font-bold text-indigo-600"><?php echo $value; ?>/10</span>
                                        <div class="flex-1 bg-slate-200 rounded-full h-2">
                                            <div class="bg-purple-600 h-2 rounded-full" style="width:<?php echo $percentage; ?>%;"></div>
                                        </div>
                                    </div>
                                </div>
                                <?php endfor; ?>
                            </div>
                            
                            <?php if (!empty($matrix_evaluation['comments'])): ?>
                                <div class="mt-3 p-3 bg-white rounded-lg">
                                    <p><strong>Comments & Recommendations:</strong></p>
                                    <p class="text-slate-600"><?php echo nl2br(htmlspecialchars($matrix_evaluation['comments'])); ?></p>
                                </div>
                            <?php endif; ?>
                            
                            <?php if (hasRole([ROLE_ADMIN, ROLE_RESEARCHER])): ?>
                            <div class="mt-3 no-print">
                                <button onclick="toggleMatrixForm()" class="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg btn-scale">
                                    <i class="fa-solid fa-pen mr-2"></i> Update Evaluation
                                </button>
                            </div>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>

                    <!-- Matrix Evaluation Form -->
                    <?php if (hasRole([ROLE_ADMIN, ROLE_RESEARCHER])): ?>
                    <div id="matrixForm" class="<?php echo $matrix_evaluation ? 'hidden' : 'block'; ?>">
                        <form method="POST" action="" id="matrixFormSubmit">
                            <input type="hidden" name="save_matrix" value="1">
                            <input type="hidden" name="benchmark_id" value="<?php echo $analysis_data['benchmark_id']; ?>">
                            
                            <div class="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
                                <p class="text-sm text-blue-700">
                                    <i class="fa-solid fa-info-circle mr-2"></i>
                                    Rate each criteria from 1 (Poor) to 10 (Excellent) based on how well the policy aligns with the legal documents.
                                    Click on a number to select your rating.
                                </p>
                            </div>
                            
                            <div class="grid md:grid-cols-2 gap-4 mb-4">
                                <?php 
                                $criteria_labels = [
                                    1 => 'Alignment with Legal Framework',
                                    2 => 'Compliance with Constitutional Provisions',
                                    3 => 'Consistency with International Law',
                                    4 => 'Protection of Rights and Liberties',
                                    5 => 'Implementation Mechanism',
                                    6 => 'Monitoring and Evaluation',
                                    7 => 'Stakeholder Engagement',
                                    8 => 'Resource Allocation',
                                    9 => 'Risk Assessment',
                                    10 => 'Sustainability'
                                ];
                                $criteria_descriptions = [
                                    1 => 'How well does the policy align with existing legal frameworks?',
                                    2 => 'Does the policy comply with constitutional provisions?',
                                    3 => 'Is the policy consistent with international law and treaties?',
                                    4 => 'How well does the policy protect rights and liberties?',
                                    5 => 'Does the policy have a clear implementation mechanism?',
                                    6 => 'Are there provisions for monitoring and evaluation?',
                                    7 => 'Does the policy ensure stakeholder engagement?',
                                    8 => 'Are resources adequately allocated for implementation?',
                                    9 => 'Has the policy undergone proper risk assessment?',
                                    10 => 'Is the policy sustainable in the long term?'
                                ];
                                
                                for ($c = 1; $c <= 10; $c++): 
                                    $current_value = $matrix_evaluation ? ($matrix_evaluation['criteria' . $c] ?? 0) : 0;
                                ?>
                                <div class="criteria-card p-4 rounded-lg">
                                    <label class="font-semibold text-slate-700 block"><?php echo $c . '. ' . $criteria_labels[$c]; ?></label>
                                    <p class="text-sm text-slate-500 mb-2"><?php echo $criteria_descriptions[$c]; ?></p>
                                    <div class="flex gap-1 flex-wrap">
                                        <?php for ($i = 1; $i <= 10; $i++): ?>
                                            <label class="cursor-pointer flex items-center gap-1">
                                                <input type="radio" name="criteria<?php echo $c; ?>" value="<?php echo $i; ?>" 
                                                    <?php echo ($current_value == $i) ? 'checked' : ''; ?> 
                                                    onchange="updateRating(this)" required>
                                                <span class="rating-number <?php echo ($current_value == $i) ? 'selected' : ''; ?>" 
                                                      onclick="handleNumberClick(this)"><?php echo $i; ?></span>
                                            </label>
                                        <?php endfor; ?>
                                    </div>
                                </div>
                                <?php endfor; ?>
                            </div>
                            
                            <div class="mb-4">
                                <label class="font-semibold text-slate-700 block mb-2">Comments / Recommendations</label>
                                <textarea name="comments" rows="3" class="w-full border rounded-lg p-3 focus:ring-2 focus:ring-purple-600" 
                                    placeholder="Add your comments and recommendations based on the comparison..."><?php echo $matrix_evaluation ? htmlspecialchars($matrix_evaluation['comments']) : ''; ?></textarea>
                            </div>
                            
                            <div class="flex gap-3">
                                <button type="submit" class="bg-purple-600 hover:bg-purple-700 text-white px-6 py-2 rounded-lg btn-scale">
                                    <i class="fa-solid fa-save mr-2"></i> Save Evaluation
                                </button>
                                <?php if ($matrix_evaluation): ?>
                                    <button type="button" onclick="toggleMatrixForm()" class="bg-slate-200 hover:bg-slate-300 text-slate-700 px-6 py-2 rounded-lg btn-scale">
                                        Cancel
                                    </button>
                                <?php endif; ?>
                            </div>
                        </form>
                    </div>
                    <?php endif; ?>
                </div>
            </div>

            <!-- FORMAL SIGNATURE / AUTHENTICATION BLOCK (PRINT ONLY) -->
            <div class="print-signature-block hidden print:flex">
                <div class="signature-col text-center">
                    <p class="text-xs text-slate-500 uppercase tracking-wider mb-8">Prepared / Analyzed By:</p>
                    <div class="signature-line border-t border-slate-900 pt-1">
                        <p class="text-xs font-bold text-slate-900"><?php echo htmlspecialchars($username ?? 'Policy Analyst'); ?></p>
                        <p class="text-[10px] text-slate-600">Legislative Research & Policy Division</p>
                    </div>
                </div>
                <div class="signature-col text-center">
                    <p class="text-xs text-slate-500 uppercase tracking-wider mb-8">Verified & Approved By:</p>
                    <div class="signature-line border-t border-slate-900 pt-1">
                        <p class="text-xs font-bold text-slate-900">Head of Policy Analysis & Benchmarking</p>
                        <p class="text-[10px] text-slate-600">City Government of San Jose Del Monte</p>
                    </div>
                </div>
            </div>

            <!-- Analysis Footer Actions -->
            <div class="flex flex-wrap items-center justify-between gap-3 p-4 px-6 border-t bg-slate-50 rounded-b-xl no-print">
                <div class="flex gap-2">
                    <button onclick="window.print()" class="bg-green-600 hover:bg-green-700 text-white px-5 py-2.5 rounded-lg btn-scale text-sm font-semibold flex items-center gap-2">
                        <i class="fa-solid fa-print"></i> Print Report
                    </button>
                    <button onclick="downloadReport('<?php echo $analysis_data['benchmark_id']; ?>')" 
                            class="bg-purple-600 hover:bg-purple-700 text-white px-5 py-2.5 rounded-lg btn-scale text-sm font-semibold flex items-center gap-2">
                        <i class="fa-solid fa-download"></i> Download Report
                    </button>
                </div>
                <button onclick="closeAnalysisModal()" class="bg-slate-200 hover:bg-slate-300 text-slate-700 px-5 py-2.5 rounded-lg btn-scale text-sm font-semibold flex items-center gap-2">
                    <i class="fa-solid fa-arrow-left"></i> Back to List
                </button>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <!-- ========================================= -->
    <!-- FOOTER -->
    <!-- ========================================= -->
    <footer class="mt-10 border-t pt-6 pb-10 text-center text-slate-500">
        <p>© <?php echo date('Y'); ?> Legislative Research, Policy Analysis, and Impact Evaluation System</p>
        <p class="mt-2">Benchmarking and Comparative Analysis Module</p>
    </footer>

</main>
</div>

<script>
    // Client-side real-time table row filter
    function liveFilterTable(query) {
        const filter = query.toLowerCase();
        const rows = document.querySelectorAll('.submission-row, .dataset-row');
        rows.forEach(row => {
            const text = row.textContent.toLowerCase();
            row.style.display = text.includes(filter) ? '' : 'none';
        });
    }

    // Close analysis modal
    function closeAnalysisModal() {
        let modal = document.getElementById('analysisModal');
        if (modal) {
            modal.style.display = 'none';
        }
        if (window.history.replaceState) {
            const cleanUrl = window.location.protocol + "//" + window.location.host + window.location.pathname;
            window.history.replaceState({path: cleanUrl}, '', cleanUrl);
        } else {
            window.location.href = 'benchmarking-analysis.php';
        }
    }

    // Toggle matrix form visibility
    function toggleMatrixForm() {
        const form = document.getElementById('matrixForm');
        if (form) {
            form.classList.toggle('hidden');
        }
    }

    // Update rating selection
    function updateRating(radio) {
        const card = radio.closest('.criteria-card');
        if (!card) return;
        
        const numbers = card.querySelectorAll('.rating-number');
        const value = parseInt(radio.value);
        
        // Remove selected class from all numbers in this card
        numbers.forEach(num => num.classList.remove('selected'));
        
        // Add selected class to the matching number
        numbers.forEach(num => {
            if (parseInt(num.textContent) === value) {
                num.classList.add('selected');
            }
        });
        
        card.classList.add('selected');
    }

    // Handle number click - properly selects the right number
    function handleNumberClick(numberElement) {
        const card = numberElement.closest('.criteria-card');
        if (!card) return;
        
        const value = parseInt(numberElement.textContent);
        const radio = card.querySelector(`input[type="radio"][value="${value}"]`);
        
        if (radio) {
            radio.checked = true;
            // Remove selected class from all numbers
            const numbers = card.querySelectorAll('.rating-number');
            numbers.forEach(num => num.classList.remove('selected'));
            // Add selected class to clicked number
            numberElement.classList.add('selected');
            card.classList.add('selected');
            
            // Update the radio button's checked state visually
            const event = new Event('change', { bubbles: true });
            radio.dispatchEvent(event);
        }
    }

    // Download report
    function downloadReport(benchmarkId) {
        const content = document.querySelector('.doc-content')?.textContent || '';
        const policyTitle = '<?php echo $analysis_data['policy_title'] ?? 'N/A'; ?>';
        
        let text = '========================================\n';
        text += 'BENCHMARKING ANALYSIS REPORT\n';
        text += '========================================\n\n';
        text += 'Benchmark ID: ' + benchmarkId + '\n';
        text += 'Policy Title: ' + policyTitle + '\n';
        text += 'Generated: ' + new Date().toLocaleString() + '\n\n';
        text += '----------------------------------------\n';
        text += 'LEGAL DOCUMENTS\n';
        text += '----------------------------------------\n\n';
        text += content;
        text += '\n\n========================================\n';

        const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'analysis_report_' + benchmarkId + '.txt';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }

    // Backdrop click and Escape key listeners
    window.onclick = function(event) {
        let modal = document.getElementById('analysisModal');
        if (event.target == modal) {
            closeAnalysisModal();
        }
    }

    window.onkeydown = function(event) {
        if (event.key === "Escape") {
            closeAnalysisModal();
        }
    }

    // Initialize rating numbers on page load
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('.criteria-card').forEach(function(card) {
            const checkedRadio = card.querySelector('input[type="radio"]:checked');
            if (checkedRadio) {
                updateRating(checkedRadio);
            }
        });
    });

    // Button hover effects
    document.querySelectorAll("button, a.btn-scale").forEach(function(el) {
        el.addEventListener("mouseenter", function() {
            this.classList.add("scale-105", "transition");
        });
        el.addEventListener("mouseleave", function() {
            this.classList.remove("scale-105");
        });
    });
</script>

</body>
</html>

<?php
$conn->close();
?>